export const data = [
  {
    code: 1,
    name: '花王',
    industry: '科学',
    numberOfPossessions: 20,
    purchasePrice: 5000,
    marketPrice: 6000,
    dividend: 150,
  },
  {
    code: 2,
    name: '大和ハウス',
    industry: '建築',
    numberOfPossessions: 30,
    purchasePrice: 3000,
    marketPrice: 2800,
    dividend: 130,
  },
  {
    code: 3,
    name: '日東富士製粉',
    industry: '食品',
    numberOfPossessions: 34,
    purchasePrice: 3500,
    marketPrice: 4500,
    dividend: 160,
  },
  {
    code: 4,
    name: '柿安本店',
    industry: '食品',
    numberOfPossessions: 50,
    purchasePrice: 2300,
    marketPrice: 2500,
    dividend: 100,
  },
  {
    code: 5,
    name: '伊藤忠商事',
    industry: '商社',
    numberOfPossessions: 13,
    purchasePrice: 2800,
    marketPrice: 4200,
    dividend: 1510,
  },
];
